{% set name = "grafana-client" %}
{% set version = "5.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/grafana_client-{{ version }}.tar.gz
  sha256: 9469afddcf89ed43da9298104595b8a9ef39fa43556058171346746fc730efef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip >=20.0
    - setuptools >=40.0
    - setuptools-scm >=4.0,<8
    - wheel
  run:
    - importlib-metadata
    - urllib3
    - python >={{ python_min }}
    - niquests >=3.4.0,<4
    - verlib2 <26.3

test:
  imports:
    - grafana_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/panodata/grafana-client
  summary: A client library for accessing the Grafana HTTP API, written in Python
  dev_url: https://github.com/panodata/grafana-client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - marie59
