{% set name = "grafana-client" %}
{% set version = "3.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grafana-client-{{ version }}.tar.gz
  sha256: 7f89b92eb63a337940dafb148d70afdc4492fd82658b529ddf0f95967e14d359

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip >=20.0
    - setuptools >=40.0
    - setuptools-scm >=4.0,<8
    - wheel
  run:
    - python >=3.8
    - requests >=2.23.0,<3
    - verlib2 ==0.2.0

test:
  imports:
    - grafana_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/panodata/grafana-client
  summary: A client library for accessing the Grafana HTTP API, written in Python
  dev_url: https://github.com/panodata/grafana-client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - marie59
