{% set name = "grafana-client" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grafana-client-{{ version }}.tar.gz
  sha256: e7da519c1c30f369018c0928df490ef20db9c253e2c4e79f2bff459437310995

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools-scm <8
    - pip
  run:
    - python >=3.6
    - requests >=2.23.0,<3
    - dataclasses
    - importlib-metadata

test:
  imports:
    - grafana_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/panodata/grafana-client
  summary: A client library for accessing the Grafana HTTP API, written in Python
  dev_url: https://github.com/panodata/grafana-client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marie59
