{% set name = "grafana-client" %}
{% set version = "4.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grafana_client-{{ version }}.tar.gz
  sha256: bafbd0ac5fdcde0a84459b650020955159385f50df82c3c7a045b4ba7936532a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip >=20.0
    - setuptools >=40.0
    - setuptools-scm >=4.0,<8
    - wheel
  run:
    - python >={{ python_min }}
    - niquests >=3.4.0,<4
    - verlib2 ==0.2.0

test:
  imports:
    - grafana_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/panodata/grafana-client
  summary: A client library for accessing the Grafana HTTP API, written in Python
  dev_url: https://github.com/panodata/grafana-client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - marie59
