{% set name = "grafana-client" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cf92886236bc85f28deb5e969692b4fa187fc36caf2ecdf524e6acf2f44e1c3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip >=20.0
    - setuptools >=40.0
    - setuptools-scm >=4.0,<8
    - wheel
  run:
    - python >=3.8
    - niquests >=3.4.0,<4
# niquests requires urllib3.future >=2.8.902,<3 urllib3-future <3,>=2.8.902 jh2 >=5.0.3,<6.0.0
    #- requests >=2.23.0,<3
    - verlib2 ==0.2.0

test:
  imports:
    - grafana_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/panodata/grafana-client
  summary: A client library for accessing the Grafana HTTP API, written in Python
  dev_url: https://github.com/panodata/grafana-client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - marie59
